In [134]:
from selenium import webdriver
from selenium.webdriver.common.by import By
import pandas as pd
import time

In [135]:
# options = webdriver.ChromeOptions()
# options.add_argument("--headless")

# driver = webdriver.Chrome(options=options)
# driver.maximize_window()

In [136]:
# reviews_data = []

In [137]:
# def get_label(stars):
#     stars = int(stars)

#     if stars >= 4:
#         return "pos"
#     elif stars <= 2:
#         return "neg"
#     else:
#         return "neutre"

In [138]:
# # 1. récupérer toutes les catégories
# categories_url = "https://fr.trustpilot.com/categories"

# driver.get(categories_url)
# time.sleep(3)

# categories = driver.find_elements(By.CLASS_NAME, "styles_container__ptvcf")

# categories_urls = []

# for category in categories:

#     elements = category.find_elements(By.TAG_NAME, "li")

#     for element in elements:

#         try:
#             href = element.find_element(By.TAG_NAME, "a").get_attribute("href")

#             if href not in categories_urls:
#                 categories_urls.append(href)

#         except:
#             continue

# print(f"{len(categories_urls)} catégories trouvées")

In [139]:
# # 2. récupérer les entreprises
# enterprise_urls = []

# for category_url in categories_urls:

#     print(f"Scraping catégorie : {category_url}")

#     current_url = category_url

#     while True:

#         driver.get(current_url)
#         time.sleep(3)

#         try:
#             cards = driver.find_elements(
#                 By.CLASS_NAME,
#                 "CDS_Card_card__146e7a"
#             )

#             for card in cards:

#                 try:
#                     businesses = card.find_elements(
#                         By.CLASS_NAME,
#                         "styles_businessUnitMain__wRgqU"
#                     )

#                     for business in businesses:

#                         try:
#                             span = business.find_element(
#                                 By.CSS_SELECTOR,
#                                 'span[role="button"]'
#                             )

#                             review_count = span.text.split(" ")[0]
#                             count = int(
#                                 review_count
#                                 .replace(" ", "")
#                                 .replace("\u202f", "")
#                             )
#                             # garder entreprises avec avis
#                             if count > 3:
#                                 href = card.find_element(
#                                     By.TAG_NAME,
#                                     "a"
#                                 ).get_attribute("href")
#                                 if href not in enterprise_urls:
#                                     enterprise_urls.append(href)

#                         except:
#                             continue

#                 except:
#                     continue
            
#             print(
#                 f"{len(enterprise_urls)} entreprises"
#             )

#             # pagination catégories
#             try:
#                 pagination = driver.find_element(
#                     By.CSS_SELECTOR,
#                     '[name="pagination-button-next"]'
#                 )

#                 next_url = pagination.get_attribute("href")

#                 if not next_url:
#                     break

#                 current_url = next_url

#             except:
#                 break

#         except Exception as e:
#             print(e)
#             break

# print(f"Total entreprises : {len(enterprise_urls)}")

In [140]:
# enterprise_urls

In [141]:
# urls = ['https://fr.trustpilot.com/review/ouwayss.com',
#  'https://fr.trustpilot.com/review/miel-lacourcelle.fr',
#  'https://fr.trustpilot.com/review/vin-alsace-gueth.com',
#  'https://fr.trustpilot.com/review/cagette.net',
#  'https://fr.trustpilot.com/review/le-lavandin.fr',
#  'https://fr.trustpilot.com/review/capspiruline.com',
#  'https://fr.trustpilot.com/review/maisondumiel.fr',
#  'https://fr.trustpilot.com/review/moillard.fr',
#  'https://fr.trustpilot.com/review/canebiera.com',
#  'https://fr.trustpilot.com/review/fruggies.com',
#  'https://fr.trustpilot.com/review/domaine-labaume.com',
#  'https://fr.trustpilot.com/review/caves-carod.com',
#  'https://fr.trustpilot.com/review/chateauberne-vin.com',
#  'https://fr.trustpilot.com/review/arthurmetz.com',
#  'https://fr.trustpilot.com/review/velleminfroy.fr',
#  'https://fr.trustpilot.com/review/agripartner.fr',
#  'https://fr.trustpilot.com/review/auxine-shop.fr',
#  'https://fr.trustpilot.com/review/franceelevage.fr',
#  'https://fr.trustpilot.com/review/lamaisondesantilles.com',
#  'https://fr.trustpilot.com/review/french-corner-shop.com',
#  'https://fr.trustpilot.com/review/laboxfromage.fr',
#  'https://fr.trustpilot.com/review/maisonduvigneron.com',
#  'https://fr.trustpilot.com/review/chezmarceline.com',
#  'https://fr.trustpilot.com/review/delozey.com',
#  'https://fr.trustpilot.com/review/hilaj.fr',
#  'https://fr.trustpilot.com/review/cuvee-privee.com',
#  'https://fr.trustpilot.com/review/miel-booster.com',
#  'https://fr.trustpilot.com/review/weedlingsfinest.com',
#  'https://fr.trustpilot.com/review/mielducap.fr',
#  'https://fr.trustpilot.com/review/www.domaine-chezelles.com',
#  'https://fr.trustpilot.com/review/fermedumoutta.fr',
#  'https://fr.trustpilot.com/review/miel-king.com',
#  'https://fr.trustpilot.com/review/chateau-de-la-riviere.com',
#  'https://fr.trustpilot.com/review/soinsathome.com',
#  'https://fr.trustpilot.com/review/chateaudefesles.com',
#  'https://fr.trustpilot.com/review/allouchery-bailly.fr',
#  'https://fr.trustpilot.com/review/lesvignoblesfoncalieu.com',
#  'https://fr.trustpilot.com/review/payzan.fr',
#  'https://fr.trustpilot.com/review/foodiab.com',
#  'https://fr.trustpilot.com/review/pourdebon.com',
#  'https://fr.trustpilot.com/review/cave-tavel-lirac.fr',
#  'https://fr.trustpilot.com/review/mesabeilles.fr',
#  'https://fr.trustpilot.com/review/laruchequiditoui.fr',
#  'https://fr.trustpilot.com/review/paturevision.fr',
#  'https://fr.trustpilot.com/review/micropousses-pro.com',
#  'https://fr.trustpilot.com/review/jardindedouard.vin',
#  'https://fr.trustpilot.com/review/bonbonrama.com',
#  'https://fr.trustpilot.com/review/myfarmbase.com',
#  'https://fr.trustpilot.com/review/terroirgaulois.fr',
#  'https://fr.trustpilot.com/review/mdb-equipement.com',
#  'https://fr.trustpilot.com/review/maisonlacheteau.com',
#  'https://fr.trustpilot.com/review/drivedescampagnes.fr',
#  'https://fr.trustpilot.com/review/uvc-champagne-sudaisne.com',
#  'https://fr.trustpilot.com/review/cannacie.com',
#  'https://fr.trustpilot.com/review/sifrais.fr',
#  'https://fr.trustpilot.com/review/king-miel.com',
#  'https://fr.trustpilot.com/review/bangoweed.fr',
#  'https://fr.trustpilot.com/review/eau-alvina.fr',
#  'https://fr.trustpilot.com/review/myamanashop.com',
#  'https://fr.trustpilot.com/review/cuscosocialclub.fr',
#  'https://fr.trustpilot.com/review/mieletmerveilles.fr',
#  'https://fr.trustpilot.com/review/rucherducabanon.com',
#  'https://fr.trustpilot.com/review/pierre-aoun-apiculteur.com',
#  'https://fr.trustpilot.com/review/agryco.com',
#  'https://fr.trustpilot.com/review/comores-en-ligne.fr',
#  'https://fr.trustpilot.com/review/agrostore.com',
#  'https://fr.trustpilot.com/review/www.culinaries.fr',
#  'https://fr.trustpilot.com/review/kosmos-bio.com',
#  'https://fr.trustpilot.com/review/famillevacher.fr',
#  'https://fr.trustpilot.com/review/mielmalaki.com',
#  'https://fr.trustpilot.com/review/cbdevor.com',
#  'https://fr.trustpilot.com/review/borde.fr',
#  'https://fr.trustpilot.com/review/lecomptoir.app',
#  'https://fr.trustpilot.com/review/aumerade.com',
#  'https://fr.trustpilot.com/review/blackhorsehoneys.com',
#  'https://fr.trustpilot.com/review/www.hn-lab.com',
#  'https://fr.trustpilot.com/review/valleedoan.com',
#  'https://fr.trustpilot.com/review/domaineericgelly.fr',
#  'https://fr.trustpilot.com/review/lacompagniedesbutineuses.com',
#  'https://fr.trustpilot.com/review/miel-bio.biz',
#  'https://fr.trustpilot.com/review/turbocereal.io',
#  'https://fr.trustpilot.com/review/wetruf.com',
#  'https://fr.trustpilot.com/review/moncomtebon.com',
#  'https://fr.trustpilot.com/review/lapapillonne.fr',
#  'https://fr.trustpilot.com/review/hellonutrifresh.com',
#  'https://fr.trustpilot.com/review/laboitedufromager.com',
#  'https://fr.trustpilot.com/review/cercledumiel.fr',
#  'https://fr.trustpilot.com/review/feuilles-tabac.fr',
#  'https://fr.trustpilot.com/review/agour.com',
#  'https://fr.trustpilot.com/review/pinknoisette.com',
#  'https://fr.trustpilot.com/review/www.lafermeduluguen.fr',
#  'https://fr.trustpilot.com/review/lite-heberg.fr',
#  'https://fr.trustpilot.com/review/miamland.com',
#  'https://fr.trustpilot.com/review/nilabeautys.com',
#  'https://fr.trustpilot.com/review/champfrance.fr',
#  'https://fr.trustpilot.com/review/rucherduclos.com',
#  'https://fr.trustpilot.com/review/highexpress.fr',
#  'https://fr.trustpilot.com/review/easyseniors.fr',
#  'https://fr.trustpilot.com/review/famillevacher.com',
#  'https://fr.trustpilot.com/review/premium-cbd.fr',
#  'https://fr.trustpilot.com/review/ginetteetjosiane.com',
#  'https://fr.trustpilot.com/review/www.prodealcenter.fr',
#  'https://fr.trustpilot.com/review/pillivuyt.fr',
#  'https://fr.trustpilot.com/review/www.ldc.fr',
#  'https://fr.trustpilot.com/review/www.fromages.com',
#  'https://fr.trustpilot.com/review/larecolte.fr',
#  'https://fr.trustpilot.com/review/lepotagerdesante.com',
#  'https://fr.trustpilot.com/review/lunedemiel.fr',
#  'https://fr.trustpilot.com/review/www.laboiteachampignons.com',
#  'https://fr.trustpilot.com/review/greenleafcbd.fr',
#  'https://fr.trustpilot.com/review/lecartelfrancais.com',
#  'https://fr.trustpilot.com/review/www.comptoirdesvignes.fr',
#  'https://fr.trustpilot.com/review/www.cavepurjus.com',
#  'https://fr.trustpilot.com/review/au-droit-de-bouchon.com',
#  'https://fr.trustpilot.com/review/www.microbrasseur.com',
#  'https://fr.trustpilot.com/review/caves-bossetti.fr',
#  'https://fr.trustpilot.com/review/lesvignoblesedonis.com',
#  'https://fr.trustpilot.com/review/1envie1vin.com',
#  'https://fr.trustpilot.com/review/quintaportuguesa.fr',
#  'https://fr.trustpilot.com/review/toulousesakeclub.com',
#  'https://fr.trustpilot.com/review/lesbieresetonnantes.fr',
#  'https://fr.trustpilot.com/review/lepetitballon.com',
#  'https://fr.trustpilot.com/review/www.vente-directe-vigneron-independant.com',
#  'https://fr.trustpilot.com/review/vintageandco.com',
#  'https://fr.trustpilot.com/review/familleperrin.com',
#  'https://fr.trustpilot.com/review/champagne-terroir.fr',
#  'https://fr.trustpilot.com/review/vignartea.fr',
#  'https://fr.trustpilot.com/review/chateau-loudenne.com',
#  'https://fr.trustpilot.com/review/lou-kombucha.fr',
#  'https://fr.trustpilot.com/review/canonchaigneau.com',
#  'https://fr.trustpilot.com/review/cavedechaz.com',
#  'https://fr.trustpilot.com/review/brottedirect.com',
#  'https://fr.trustpilot.com/review/winenex.com',
#  'https://fr.trustpilot.com/review/ventealapropriete.com',
#  'https://fr.trustpilot.com/review/lavinia.com',
#  'https://fr.trustpilot.com/review/chateaunet.com',
#  'https://fr.trustpilot.com/review/sommelleriedefrance.com',
#  'https://fr.trustpilot.com/review/tresorsdebacchus.com',
#  'https://fr.trustpilot.com/review/www.winalist.com',
#  'https://fr.trustpilot.com/review/urban-drinks.fr',
#  'https://fr.trustpilot.com/review/pro.plugwine.com',
#  'https://fr.trustpilot.com/review/www.troisfoisvin.com',
#  'https://fr.trustpilot.com/review/winesitting.com',
#  'https://fr.trustpilot.com/review/alenti.fr',
#  'https://fr.trustpilot.com/review/www.les2cavistes.fr',
#  'https://fr.trustpilot.com/review/climadiff.com',
#  'https://fr.trustpilot.com/review/www.lasommeliere.com',
#  'https://fr.trustpilot.com/review/lebaroudeurduvin.com',
#  'https://fr.trustpilot.com/review/www.shop.pierre-chavin.com',
#  'https://fr.trustpilot.com/review/www.labellevie.com',
#  'https://fr.trustpilot.com/review/laboxavin.fr',
#  'https://fr.trustpilot.com/review/produits-normandie.fr',
#  'https://fr.trustpilot.com/review/www.vin-malin.fr',
#  'https://fr.trustpilot.com/review/www.symbiose-kefir.fr',
#  'https://fr.trustpilot.com/review/demainlesvins.com',
#  'https://fr.trustpilot.com/review/stephconti.fr',
#  'https://fr.trustpilot.com/review/www.rolling-beers.fr',
#  'https://fr.trustpilot.com/review/wepicurien.com',
#  'https://fr.trustpilot.com/review/abacchus.fr',
#  'https://fr.trustpilot.com/review/e-winery.fr',
#  'https://fr.trustpilot.com/review/cavacave.com',
#  'https://fr.trustpilot.com/review/whynat.fr',
#  'https://fr.trustpilot.com/review/lebongustave.com',
#  'https://fr.trustpilot.com/review/clicknschluck.fr',
#  'https://fr.trustpilot.com/review/premiumvinum.com',
#  'https://fr.trustpilot.com/review/via-vinum.com',
#  'https://fr.trustpilot.com/review/www.jean-merlaut.com',
#  'https://fr.trustpilot.com/review/rb-and-beer.com',
#  'https://fr.trustpilot.com/review/vinothequeduleman.fr',
#  'https://fr.trustpilot.com/review/www.winerepublik.com',
#  'https://fr.trustpilot.com/review/lechantdescaves.com',
#  'https://fr.trustpilot.com/review/maisonbagarre.fr',
#  'https://fr.trustpilot.com/review/festicave.com',
#  'https://fr.trustpilot.com/review/www.vino-iberico.com',
#  'https://fr.trustpilot.com/review/la-cave-cellar.com',
#  'https://fr.trustpilot.com/review/lecarredesvins.com',
#  'https://fr.trustpilot.com/review/valleybio.fr',
#  'https://fr.trustpilot.com/review/levintelckel.fr',
#  'https://fr.trustpilot.com/review/lespepitesbybb.com',
#  'https://fr.trustpilot.com/review/domaine-adam.com',
#  'https://fr.trustpilot.com/review/www.bienmanger.com',
#  'https://fr.trustpilot.com/review/unepetitemousse.fr',
#  'https://fr.trustpilot.com/review/www.chateau.fr',
#  'https://fr.trustpilot.com/review/calyce-cidre.com',
#  'https://fr.trustpilot.com/review/argicru-france.com',
#  'https://fr.trustpilot.com/review/brasseriedefrance.com',
#  'https://fr.trustpilot.com/review/champagne-de-vignerons.com',
#  'https://fr.trustpilot.com/review/buetapprouve.com',
#  'https://fr.trustpilot.com/review/vignobles-coudert.com',
#  'https://fr.trustpilot.com/review/atelierspirit.fr',
#  'https://fr.trustpilot.com/review/chamvermeil.com/fr-fr',
#  'https://fr.trustpilot.com/review/divvino.com',
#  'https://fr.trustpilot.com/review/forvm.fr',
#  'https://fr.trustpilot.com/review/cavejuste.fr',
#  'https://fr.trustpilot.com/review/u.wine',
#  'https://fr.trustpilot.com/review/hopjoy.fr',
#  'https://fr.trustpilot.com/review/bar-spirit-shop.com',
#  'https://fr.trustpilot.com/review/domainedevenus.com',
#  'https://fr.trustpilot.com/review/www.plus-de-bulles.com',
#  'https://fr.trustpilot.com/review/samepho.com',
#  'https://fr.trustpilot.com/review/le-vin-cote-femmes.com',
#  'https://fr.trustpilot.com/review/wine-day-tours.com',
#  'https://fr.trustpilot.com/review/jusdegoutte.com',
#  'https://fr.trustpilot.com/review/23vins.com',
#  'https://fr.trustpilot.com/review/le-petit-baroudeur.com',
#  'https://fr.trustpilot.com/review/domainedugout.com',
#  'https://fr.trustpilot.com/review/ladamebleue.com',
#  'https://fr.trustpilot.com/review/les-degustations-de-marion.com',
#  'https://fr.trustpilot.com/review/free-my-beer.com',
#  'https://fr.trustpilot.com/review/vinogram.fr',
#  'https://fr.trustpilot.com/review/jecreemacave.com',
#  'https://fr.trustpilot.com/review/pleasurewine.com',
#  'https://fr.trustpilot.com/review/champagnephilippedechelle.com',
#  'https://fr.trustpilot.com/review/millesima.fr',
#  'https://fr.trustpilot.com/review/lacavedepauline.com',
#  'https://fr.trustpilot.com/review/www.prestigemillesimes.fr',
#  'https://fr.trustpilot.com/review/goodness.wine',
#  'https://fr.trustpilot.com/review/levindecheznous.com',
#  'https://fr.trustpilot.com/review/www.des-racines-au-verre.fr',
#  'https://fr.trustpilot.com/review/www.velvetbull.fr',
#  'https://fr.trustpilot.com/review/vinchezmoi.com',
#  'https://fr.trustpilot.com/review/lesgrappes.com',
#  'https://fr.trustpilot.com/review/www.vignapart.com',
#  'https://fr.trustpilot.com/review/drinksco.fr',
#  'https://fr.trustpilot.com/review/le-moderato.com',
#  'https://fr.trustpilot.com/review/vandb.fr',
#  'https://fr.trustpilot.com/review/mycaviste.com',
#  'https://fr.trustpilot.com/review/mespetitsvignerons.com',
#  'https://fr.trustpilot.com/review/ventealapropriete.be',
#  'https://fr.trustpilot.com/review/vinsolite.fr',
#  'https://fr.trustpilot.com/review/josettedegustation.com',
#  'https://fr.trustpilot.com/review/vilavigne.fr',
#  'https://fr.trustpilot.com/review/retourdevignes.fr',
#  'https://fr.trustpilot.com/review/origivino.com',
#  'https://fr.trustpilot.com/review/klaxxbrewing.com',
#  'https://fr.trustpilot.com/review/coffret-divin.com',
#  'https://fr.trustpilot.com/review/shababik.shop',
#  'https://fr.trustpilot.com/review/ledecante.fr',
#  'https://fr.trustpilot.com/review/valap.it',
#  'https://fr.trustpilot.com/review/vinbox.fr',
#  'https://fr.trustpilot.com/review/boutique.chateaucapion.com',
#  'https://fr.trustpilot.com/review/valap.de',
#  'https://fr.trustpilot.com/review/cocomiette.com',
#  'https://fr.trustpilot.com/review/crush-la-cave.fr',
#  'https://fr.trustpilot.com/review/caves-saint-poloises.fr',
#  'https://fr.trustpilot.com/review/lacavedesplaisirsgourmands.fr',
#  'https://fr.trustpilot.com/review/vinatis.com',
#  'https://fr.trustpilot.com/review/heritage-whisky.fr',
#  'https://fr.trustpilot.com/review/lescavesavin.com',
#  'https://fr.trustpilot.com/review/mabouteille.fr',
#  'https://fr.trustpilot.com/review/littlewood.fr',
#  'https://fr.trustpilot.com/review/enviedechamp.com',
#  'https://fr.trustpilot.com/review/copainscommeraisins.com',
#  'https://fr.trustpilot.com/review/eastern-wine.com',
#  'https://fr.trustpilot.com/review/vinroyal.fr',
#  'https://fr.trustpilot.com/review/chateau.com',
#  'https://fr.trustpilot.com/review/ma-cave-a-vin.fr',
#  'https://fr.trustpilot.com/review/calais-vins.com',
#  'https://fr.trustpilot.com/review/vendezvosvins.fr',
#  'https://fr.trustpilot.com/review/pomerol.com',
#  'https://fr.trustpilot.com/review/valap.es',
#  'https://fr.trustpilot.com/review/www.vinovalie.com',
#  'https://fr.trustpilot.com/review/www.publicisdrugstore.com',
#  'https://fr.trustpilot.com/review/winy.store',
#  'https://fr.trustpilot.com/review/puretaste.fr',
#  'https://fr.trustpilot.com/review/terroirs-de-savoie.fr',
#  'https://fr.trustpilot.com/review/www.vinsgrandscrus.fr',
#  'https://fr.trustpilot.com/review/beaujolaistore.fr',
#  'https://fr.trustpilot.com/review/www.fauchon.com',
#  'https://fr.trustpilot.com/review/www.excellencerhum.com',
#  'https://fr.trustpilot.com/review/lacoupole-paris.com',
#  'https://fr.trustpilot.com/review/twil.fr',
#  'https://fr.trustpilot.com/review/krosno-france.com',
#  'https://fr.trustpilot.com/review/drankdozijn.fr',
#  'https://fr.trustpilot.com/review/oeforgood.com',
#  'https://fr.trustpilot.com/review/lespassionnesduvin.com',
#  'https://fr.trustpilot.com/review/chaisdoeuvre.fr',
#  'https://fr.trustpilot.com/review/www.arbre-a-biere.fr',
#  'https://fr.trustpilot.com/review/www.viniphile.fr',
#  'https://fr.trustpilot.com/review/pernod-ricard.com',
#  'https://fr.trustpilot.com/review/lartdelabiere.fr',
#  'https://fr.trustpilot.com/review/chateauinternet.com',
#  'https://fr.trustpilot.com/review/www.foie-gras-sarlat.com',
#  'https://fr.trustpilot.com/review/svinando.fr',
#  'https://fr.trustpilot.com/review/1jour1vin.com',
#  'https://fr.trustpilot.com/review/seulementproduitsitaliens.fr',
#  'https://fr.trustpilot.com/review/xo-vin.fr',
#  'https://fr.trustpilot.com/review/boboco.fr',
#  'https://fr.trustpilot.com/review/lecanonfrancais.com',
#  'https://fr.trustpilot.com/review/www.3brasseurs.com',
#  'https://fr.trustpilot.com/review/vinsetchampagne.fr',
#  'https://fr.trustpilot.com/review/bernabei.fr',
#  'https://fr.trustpilot.com/review/vinero.fr',
#  'https://fr.trustpilot.com/review/www.lalandemoreau.com',
#  'https://fr.trustpilot.com/review/lavignery.fr',
#  'https://fr.trustpilot.com/review/oenocar.fr',
#  'https://fr.trustpilot.com/review/www.vin-subtil.com',
#  'https://fr.trustpilot.com/review/www.labierepression.fr',
#  'https://fr.trustpilot.com/review/www.hopt.it',
#  'https://fr.trustpilot.com/review/www.boutiquechopetabiere.fr',
#  'https://fr.trustpilot.com/review/phileasstravinarius.com',
#  'https://fr.trustpilot.com/review/hopt.nl',
#  'https://fr.trustpilot.com/review/vina-shop.fr',
#  'https://fr.trustpilot.com/review/www.myvitibox.com',
#  'https://fr.trustpilot.com/review/maitre-georges.com',
#  'https://fr.trustpilot.com/review/www.leon-de-bruxelles.fr',
#  'https://fr.trustpilot.com/review/cavissima.com',
#  'https://fr.trustpilot.com/review/www.mybeers.fr',
#  'https://fr.trustpilot.com/review/macave.carrefour.fr',
#  'https://fr.trustpilot.com/review/www.chateauonline.fr',
#  'https://fr.trustpilot.com/review/www.nicolas.com',
#  'https://fr.trustpilot.com/review/latelierdesbieres.fr',
#  'https://fr.trustpilot.com/review/mesvinscacher.com',
#  'https://fr.trustpilot.com/review/lefourgon.com',
#  'https://fr.trustpilot.com/review/passion-rhum.com',
#  'https://fr.trustpilot.com/review/distilleriedelort.com',
#  'https://fr.trustpilot.com/review/vitis-epicuria.com',
#  'https://fr.trustpilot.com/review/bonjourdrink.co',
#  'https://fr.trustpilot.com/review/semineraliser.com',
#  'https://fr.trustpilot.com/review/originalmate.fr',
#  'https://fr.trustpilot.com/review/ensuite.fr',
#  'https://fr.trustpilot.com/review/eauriginelle.com',
#  'https://fr.trustpilot.com/review/nokamatcha.com',
#  'https://fr.trustpilot.com/review/fumoir-angresse.fr',
#  'https://fr.trustpilot.com/review/camus.fr',
#  'https://fr.trustpilot.com/review/comptoir-irlandais.com',
#  'https://fr.trustpilot.com/review/www.madeincalvados.com',
#  'https://fr.trustpilot.com/review/arseneboissons.fr',
#  'https://fr.trustpilot.com/review/veegreen.fr',
#  'https://fr.trustpilot.com/review/www.la-tournee.co',
#  'https://fr.trustpilot.com/review/lxir-drink.com',
#  'https://fr.trustpilot.com/review/al-origin.fr',
#  'https://fr.trustpilot.com/review/cherico.fr',
#  'https://fr.trustpilot.com/review/www.lesartistesparis.com',
#  'https://fr.trustpilot.com/review/rezenergydrink.com',
#  'https://fr.trustpilot.com/review/basilurteafrance.fr',
#  'https://fr.trustpilot.com/review/sensaterra.com',
#  'https://fr.trustpilot.com/review/maisonlauze.com',
#  'https://fr.trustpilot.com/review/pure-tea.co',
#  'https://fr.trustpilot.com/review/chateaudeau.com',
#  'https://fr.trustpilot.com/review/toutautourduvin.fr',
#  'https://fr.trustpilot.com/review/chabiothe.fr',
#  'https://fr.trustpilot.com/review/www.rhumattitude.com',
#  'https://fr.trustpilot.com/review/humbleplus.com',
#  'https://fr.trustpilot.com/review/ragnarok-store.fr',
#  'https://fr.trustpilot.com/review/drinknuoro.com',
#  'https://fr.trustpilot.com/review/whiskyrozelieures.com',
#  'https://fr.trustpilot.com/review/drinkdong.com',
#  'https://fr.trustpilot.com/review/spiriterie.com',
#  'https://fr.trustpilot.com/review/coquetelers.fr',
#  'https://fr.trustpilot.com/review/lesboxdecotevignes.fr',
#  'https://fr.trustpilot.com/review/lcmb.fr',
#  'https://fr.trustpilot.com/review/rsp-wine.com',
#  'https://fr.trustpilot.com/review/fancycellar.fr',
#  'https://fr.trustpilot.com/review/shobi.fr',
#  'https://fr.trustpilot.com/review/lanotesauvage.fr',
#  'https://fr.trustpilot.com/review/adnwinespirit.com',
#  'https://fr.trustpilot.com/review/dizane.fr',
#  'https://fr.trustpilot.com/review/monwhisky.fr',
#  'https://fr.trustpilot.com/review/fils-de-pomme.com',
#  'https://fr.trustpilot.com/review/mysterytea.shop',
#  'https://fr.trustpilot.com/review/cavedantoine.com',
#  'https://fr.trustpilot.com/review/thecocktailist.fr',
#  'https://fr.trustpilot.com/review/www.nighthawks.fr',
#  'https://fr.trustpilot.com/review/worldgrandscrus.com',
#  'https://fr.trustpilot.com/review/helsi.fr',
#  'https://fr.trustpilot.com/review/shop.owned-esport.fr',
#  'https://fr.trustpilot.com/review/hellodrinks.fr',
#  'https://fr.trustpilot.com/review/lemagicienbio.fr',
#  'https://fr.trustpilot.com/review/sodastream.fr',
#  'https://fr.trustpilot.com/review/lavie.bio',
#  'https://fr.trustpilot.com/review/leclubbulles.fr',
#  'https://fr.trustpilot.com/review/thewhiskycollectors.com',
#  'https://fr.trustpilot.com/review/amourduvin.com',
#  'https://fr.trustpilot.com/review/osake.fr',
#  'https://fr.trustpilot.com/review/wakaze-sake.com',
#  'https://fr.trustpilot.com/review/altcellars.com',
#  'https://fr.trustpilot.com/review/lacaveconfidentielle.com',
#  'https://fr.trustpilot.com/review/bellavinea.com',
#  'https://fr.trustpilot.com/review/maisonbam.com',
#  'https://fr.trustpilot.com/review/pepitesdevin.com',
#  'https://fr.trustpilot.com/review/iod.fr',
#  'https://fr.trustpilot.com/review/idealwine.com',
#  'https://fr.trustpilot.com/review/hydrology.fr',
#  'https://fr.trustpilot.com/review/tikiosk.fr',
#  'https://fr.trustpilot.com/review/lescookiesdekelly.fr',
#  'https://fr.trustpilot.com/review/bibo-boissons.fr',
#  'https://fr.trustpilot.com/review/vanilusso.fr',
#  'https://fr.trustpilot.com/review/aquanomade.com',
#  'https://fr.trustpilot.com/review/vinerosa.com',
#  'https://fr.trustpilot.com/review/ohmybrunch.fr',
#  'https://fr.trustpilot.com/review/www.snaqz.fr',
#  'https://fr.trustpilot.com/review/flakon.fr',
#  'https://fr.trustpilot.com/review/jane-store.com',
#  'https://fr.trustpilot.com/review/boutique.loron.fr',
#  'https://fr.trustpilot.com/review/lecoqtoque.com',
#  'https://fr.trustpilot.com/review/xwater.fr',
#  'https://fr.trustpilot.com/review/laboiteacanons.fr',
#  'https://fr.trustpilot.com/review/jede-france.com',
#  'https://fr.trustpilot.com/review/monablofr.com',
#  'https://fr.trustpilot.com/review/encoreplusrhum.com',
#  'https://fr.trustpilot.com/review/traiteur-hayraud.fr',
#  'https://fr.trustpilot.com/review/lagouttesucree.fr',
#  'https://fr.trustpilot.com/review/soleia-nice.com',
#  'https://fr.trustpilot.com/review/privatewhiskysociety.com',
#  'https://fr.trustpilot.com/review/lacouleurduvin.fr',
#  'https://fr.trustpilot.com/review/lamaisonduclairin.com',
#  'https://fr.trustpilot.com/review/consignerie.com',
#  'https://fr.trustpilot.com/review/king-mate.com',
#  'https://fr.trustpilot.com/review/moris.paris',
#  'https://fr.trustpilot.com/review/aubongin.fr',
#  'https://fr.trustpilot.com/review/www.spadella.fr',
#  'https://fr.trustpilot.com/review/wyno.io',
#  'https://fr.trustpilot.com/review/easyshop-usa.com',
#  'https://fr.trustpilot.com/review/moona-france.fr',
#  'https://fr.trustpilot.com/review/www.speedapero.com',
#  'https://fr.trustpilot.com/review/gerard-bertrand.com',
#  'https://fr.trustpilot.com/review/v2vin.com',
#  'https://fr.trustpilot.com/review/alphonseetmadeleine.com',
#  'https://fr.trustpilot.com/review/theblinewater.com',
#  'https://fr.trustpilot.com/review/neat-cocktail.com',
#  'https://fr.trustpilot.com/review/focusenergydrink.fr',
#  'https://fr.trustpilot.com/review/grinsid.com',
#  'https://fr.trustpilot.com/review/we-love-bubbles.fr',
#  'https://fr.trustpilot.com/review/rhum-damour.com',
#  'https://fr.trustpilot.com/review/www.vinduo.com',
#  'https://fr.trustpilot.com/review/arm-cool.fr',
#  'https://fr.trustpilot.com/review/www.cocktailissimo.com',
#  'https://fr.trustpilot.com/review/ultrapop.com',
#  'https://fr.trustpilot.com/review/quaisud.com',
#  'https://fr.trustpilot.com/review/gariguettes.fr',
#  'https://fr.trustpilot.com/review/althee.co',
#  'https://fr.trustpilot.com/review/tarrhamann.com',
#  'https://fr.trustpilot.com/review/atheleti.com',
#  'https://fr.trustpilot.com/review/brunchytime.fr',
#  'https://fr.trustpilot.com/review/crazyfoodshop.fr',
#  'https://fr.trustpilot.com/review/www.1336.fr',
#  'https://fr.trustpilot.com/review/ubemi.fr',
#  'https://fr.trustpilot.com/review/www.crhum.fr',
#  'https://fr.trustpilot.com/review/purple-ube.com',
#  'https://fr.trustpilot.com/review/tilolo.fr',
#  'https://fr.trustpilot.com/review/www.mr-matin.fr',
#  'https://fr.trustpilot.com/review/tullibardine.com',
#  'https://fr.trustpilot.com/review/aquacionna.com',
#  'https://fr.trustpilot.com/review/bobapop.fr',
#  'https://fr.trustpilot.com/review/lesvinsdabbayes.com',
#  'https://fr.trustpilot.com/review/unebellejournee.fr',
#  'https://fr.trustpilot.com/review/queuedecoq.com',
#  'https://fr.trustpilot.com/review/kavavin.fr',
#  'https://fr.trustpilot.com/review/whiskyparis.com',
#  'https://fr.trustpilot.com/review/www.fizzybomb.fr',
#  'https://fr.trustpilot.com/review/tucanarias.com',
#  'https://fr.trustpilot.com/review/www.barabib.com',
#  'https://fr.trustpilot.com/review/mizora-on.fr',
#  'https://fr.trustpilot.com/review/alcoool.fr',
#  'https://fr.trustpilot.com/review/d0se.fr',
#  'https://fr.trustpilot.com/review/www.ubelatteclub.com',
#  'https://fr.trustpilot.com/review/drinkjomo.com',
#  'https://fr.trustpilot.com/review/www.purezza.fr',
#  'https://fr.trustpilot.com/review/hometoq.com',
#  'https://fr.trustpilot.com/review/cazemajouvinsetspiritueux.com',
#  'https://fr.trustpilot.com/review/aquachiara.com',
#  'https://fr.trustpilot.com/review/les-caves.fr',
#  'https://fr.trustpilot.com/review/wines-friends.com',
#  'https://fr.trustpilot.com/review/lamaisonrusse.com',
#  'https://fr.trustpilot.com/review/www.prestigewhisky.fr',
#  'https://fr.trustpilot.com/review/thecoconut-tree.com',
#  'https://fr.trustpilot.com/review/monin.fr',
#  'https://fr.trustpilot.com/review/boutique.destinationcocktails.fr',
#  'https://fr.trustpilot.com/review/maisoncocktail.fr',
#  'https://fr.trustpilot.com/review/hedisonparis.com',
#  'https://fr.trustpilot.com/review/www.foodles.co',
#  'https://fr.trustpilot.com/review/www.roomsaveurs.fr',
#  'https://fr.trustpilot.com/review/www.leparadisdufruit.fr',
#  'https://fr.trustpilot.com/review/aperolemans.fr',
#  'https://fr.trustpilot.com/review/www.detoximix.com',
#  'https://fr.trustpilot.com/review/www.france-boissons.fr',
#  'https://fr.trustpilot.com/review/poulaillon.fr',
#  'https://fr.trustpilot.com/review/www.schweppes.fr',
#  'https://fr.trustpilot.com/review/www.moneaucristaline.fr',
#  'https://fr.trustpilot.com/review/lebarapapa.com',
#  'https://fr.trustpilot.com/review/www.pompe-a-biere.com',
#  'https://fr.trustpilot.com/review/www.capri-sun.com',
#  'https://fr.trustpilot.com/review/entrepotitalien.fr',
#  'https://fr.trustpilot.com/review/www.comptoirdesflandres.com',
#  'https://fr.trustpilot.com/review/medicis.fr',
#  'https://fr.trustpilot.com/review/www.leschocolatsducoeur.fr',
#  'https://fr.trustpilot.com/review/www.les-chevaliers-dargouges.com',
#  'https://fr.trustpilot.com/review/marouchocolate.com',
#  'https://fr.trustpilot.com/review/rrraw.fr',
#  'https://fr.trustpilot.com/review/shouka-chamonix.fr',
#  'https://fr.trustpilot.com/review/carre-suisse.com',
#  'https://fr.trustpilot.com/review/lareglisserie.fr',
#  'https://fr.trustpilot.com/review/www.milleproduits.com',
#  'https://fr.trustpilot.com/review/nolaconfiserie.fr',
#  'https://fr.trustpilot.com/review/curegourmande.fr',
#  'https://fr.trustpilot.com/review/lafabriqueanuage.com',
#  'https://fr.trustpilot.com/review/www.papabubble.fr',
#  'https://fr.trustpilot.com/review/lafermeauchocolat.shop',
#  'https://fr.trustpilot.com/review/auroremarket.fr',
#  'https://fr.trustpilot.com/review/lestroisreliques.com',
#  'https://fr.trustpilot.com/review/brancheparis.com',
#  'https://fr.trustpilot.com/review/lasucette.com',
#  'https://fr.trustpilot.com/review/millours.fr',
#  'https://fr.trustpilot.com/review/douceur-sucree.com',
#  'https://fr.trustpilot.com/review/lebarapop.com',
#  'https://fr.trustpilot.com/review/www.laurmar.fr',
#  'https://fr.trustpilot.com/review/candy-kids.fr',
#  'https://fr.trustpilot.com/review/myamericanmarket.com',
#  'https://fr.trustpilot.com/review/joursheureux.fr',
#  'https://fr.trustpilot.com/review/dlys-couleurs.com',
#  'https://fr.trustpilot.com/review/www.bonbonsetdouceurs.fr',
#  'https://fr.trustpilot.com/review/michelbelin.com',
#  'https://fr.trustpilot.com/review/flowersboxchocolats.fr',
#  'https://fr.trustpilot.com/review/ilantaieb.podia.com',
#  'https://fr.trustpilot.com/review/sms-bonbon.com',
#  'https://fr.trustpilot.com/review/www.lamaisonduchocolat.com',
#  'https://fr.trustpilot.com/review/bitecone.com',
#  'https://fr.trustpilot.com/review/fizzy.fr',
#  'https://fr.trustpilot.com/review/arcencieldegour.fr',
#  'https://fr.trustpilot.com/review/sweets-delivered.co.uk',
#  'https://fr.trustpilot.com/review/parenthesecafe.fr',
#  'https://fr.trustpilot.com/review/puyricard.fr',
#  'https://fr.trustpilot.com/review/omie.fr',
#  'https://fr.trustpilot.com/review/www.planetbonbons.fr',
#  'https://fr.trustpilot.com/review/www.mms.com',
#  'https://fr.trustpilot.com/review/lollys.fr',
#  'https://fr.trustpilot.com/review/confiserie-foraine.com',
#  'https://fr.trustpilot.com/review/mariadelaorden.com',
#  'https://fr.trustpilot.com/review/fabrice-gillotte.fr',
#  'https://fr.trustpilot.com/review/www.laromainville.fr',
#  'https://fr.trustpilot.com/review/www.jeanpaulhevin.com',
#  'https://fr.trustpilot.com/review/faller.fr',
#  'https://fr.trustpilot.com/review/oililyworld.com',
#  'https://fr.trustpilot.com/review/popsamerica.com',
#  'https://fr.trustpilot.com/review/quartzboutique.fr',
#  'https://fr.trustpilot.com/review/www.clementfaugier.fr',
#  'https://fr.trustpilot.com/review/www.chocolat-chapon.com',
#  'https://fr.trustpilot.com/review/ricola.com',
#  'https://fr.trustpilot.com/review/bonbonsgourmands.fr',
#  'https://fr.trustpilot.com/review/chocolats-voisin.fr',
#  'https://fr.trustpilot.com/review/www.highlandchocolatier.com',
#  'https://fr.trustpilot.com/review/reaute-chocolat.com',
#  'https://fr.trustpilot.com/review/www.fossier.fr',
#  'https://fr.trustpilot.com/review/www.cotedor-chocolat.fr',
#  'https://fr.trustpilot.com/review/desserts-montblanc.fr',
#  'https://fr.trustpilot.com/review/www.domori.com',
#  'https://fr.trustpilot.com/review/www.alexolivier.fr',
#  'https://fr.trustpilot.com/review/haagen-dazs.fr',
#  'https://fr.trustpilot.com/review/chocolat-deneuville.com',
#  'https://fr.trustpilot.com/review/www.lagrandeepicerie.com',
#  'https://fr.trustpilot.com/review/www.lecomptoirdemathilde.com',
#  'https://fr.trustpilot.com/review/abtey.fr',
#  'https://fr.trustpilot.com/review/laboutiqueharibo.fr',
#  'https://fr.trustpilot.com/review/leonidas.fr',
#  'https://fr.trustpilot.com/review/www.atelierduchocolat.fr',
#  'https://fr.trustpilot.com/review/chocolissimo.fr',
#  'https://fr.trustpilot.com/review/valgourmand.com',
#  'https://fr.trustpilot.com/review/kitkat.fr',
#  'https://fr.trustpilot.com/review/ferrero.fr',
#  'https://fr.trustpilot.com/review/snackme-chocolate.com',
#  'https://fr.trustpilot.com/review/lesaventuriersdubiscuit.com',
#  'https://fr.trustpilot.com/review/www.planete-gateau.com',
#  'https://fr.trustpilot.com/review/yacon.co',
#  'https://fr.trustpilot.com/review/galettes-penven.com',
#  'https://fr.trustpilot.com/review/ookies.fr',
#  'https://fr.trustpilot.com/review/lefrenchbiscuit.fr',
#  'https://fr.trustpilot.com/review/augoust.com',
#  'https://fr.trustpilot.com/review/patisseriepeigne.fr',
#  'https://fr.trustpilot.com/review/www.meilleurduchef.com',
#  'https://fr.trustpilot.com/review/cuisineaddict.com',
#  'https://fr.trustpilot.com/review/neigeebene.com',
#  'https://fr.trustpilot.com/review/cookizh.com',
#  'https://fr.trustpilot.com/review/pretagarnir.com',
#  'https://fr.trustpilot.com/review/monpainbio.com',
#  'https://fr.trustpilot.com/review/www.misterustensile.com',
#  'https://fr.trustpilot.com/review/ateliersdeludo.fr',
#  'https://fr.trustpilot.com/review/laboetgato.fr',
#  'https://fr.trustpilot.com/review/jeannette1850.com',
#  'https://fr.trustpilot.com/review/lesnouvellesdelaboulangerie.fr',
#  'https://fr.trustpilot.com/review/sundayroutine.fr',
#  'https://fr.trustpilot.com/review/lessecretsdegeoffrey.fr',
#  'https://fr.trustpilot.com/review/foucadeparis.fr',
#  'https://fr.trustpilot.com/review/pamperedchef.fr',
#  'https://fr.trustpilot.com/review/autourdugateau.fr',
#  'https://fr.trustpilot.com/review/lenounoursfrancais.fr',
#  'https://fr.trustpilot.com/review/dream-pastry.fr',
#  'https://fr.trustpilot.com/review/lesbiscuitsdemrlaurent.com',
#  'https://fr.trustpilot.com/review/kaake.fr',
#  'https://fr.trustpilot.com/review/tiekula.fr',
#  'https://fr.trustpilot.com/review/latoquedor.com',
#  'https://fr.trustpilot.com/review/lacookizerie.com',
#  'https://fr.trustpilot.com/review/youpeas.com',
#  'https://fr.trustpilot.com/review/lepetitbiscuitfrancais.fr',
#  'https://fr.trustpilot.com/review/dooooble.com',
#  'https://fr.trustpilot.com/review/charlycooks.myshopify.com',
#  'https://fr.trustpilot.com/review/www.abribatelectromenager.fr',
#  'https://fr.trustpilot.com/review/pastrycare.fr',
#  'https://fr.trustpilot.com/review/basbread.com',
#  'https://fr.trustpilot.com/review/gourmandisesdupalais.com',
#  'https://fr.trustpilot.com/review/www.eurolam-thiers.com',
#  'https://fr.trustpilot.com/review/allocakes.com',
#  'https://fr.trustpilot.com/review/lebrun.fr',
#  'https://fr.trustpilot.com/review/keladeco.com',
#  'https://fr.trustpilot.com/review/melcooking.com',
#  'https://fr.trustpilot.com/review/www.la-toque-cuivree.fr',
#  'https://fr.trustpilot.com/review/www.konditorei-mueller.com',
#  'https://fr.trustpilot.com/review/bagelstein.com',
#  'https://fr.trustpilot.com/review/boulangerie.org',
#  'https://fr.trustpilot.com/review/www.lamiecaline.com',
#  'https://fr.trustpilot.com/review/www.fiasconaro.com',
#  'https://fr.trustpilot.com/review/cuisineactuelle.fr',
#  'https://fr.trustpilot.com/review/www.briochedoree.fr',
#  'https://fr.trustpilot.com/review/www.columbuscafe.com',
#  'https://fr.trustpilot.com/review/pasquier.fr',
#  'https://fr.trustpilot.com/review/harrys.fr',
#  'https://fr.trustpilot.com/review/cakemaster.fr',
#  'https://fr.trustpilot.com/review/feuillette.fr',
#  'https://fr.trustpilot.com/review/masterlead.fr',
#  'https://fr.trustpilot.com/review/www.paul.fr',
#  'https://fr.trustpilot.com/review/bella-home.com',
#  'https://fr.trustpilot.com/review/www.deco-relief.fr',
#  'https://fr.trustpilot.com/review/cookfirst.fr',
#  'https://fr.trustpilot.com/review/www.boulangerie-ange.fr',
#  'https://fr.trustpilot.com/review/laduree.com',
#  'https://fr.trustpilot.com/review/www.vahine.fr',
#  'https://fr.trustpilot.com/review/www.cuisineaz.com',
#  'https://fr.trustpilot.com/review/rosieres.fr',
#  'https://fr.trustpilot.com/review/www.marmiton.org',
#  'https://fr.trustpilot.com/review/vert-tiges.com',
#  'https://fr.trustpilot.com/review/cafesbelleville.com',
#  'https://fr.trustpilot.com/review/layac.fr',
#  'https://fr.trustpilot.com/review/bruleriedesgraves.fr',
#  'https://fr.trustpilot.com/review/monjolibio.com',
#  'https://fr.trustpilot.com/review/pleyce.com',
#  'https://fr.trustpilot.com/review/boutique.nature-partage.com',
#  'https://fr.trustpilot.com/review/malongo.com',
#  'https://fr.trustpilot.com/review/cafe-en-grain.com',
#  'https://fr.trustpilot.com/review/boutique.lushan.fr',
#  'https://fr.trustpilot.com/review/larbreacafe.com',
#  'https://fr.trustpilot.com/review/thevertcitron.com',
#  'https://fr.trustpilot.com/review/pakayamba.com',
#  'https://fr.trustpilot.com/review/www.lebeauthe.com',
#  'https://fr.trustpilot.com/review/miliamatcha.com',
#  'https://fr.trustpilot.com/review/teaheritage.fr',
#  'https://fr.trustpilot.com/review/ayuin.fr',
#  'https://fr.trustpilot.com/review/cbd-certified.com',
#  'https://fr.trustpilot.com/review/freecoffee.io',
#  'https://fr.trustpilot.com/review/le-green-spot.com',
#  'https://fr.trustpilot.com/review/capsme.fr',
#  'https://fr.trustpilot.com/review/www.comptoirsrichard.fr',
#  'https://fr.trustpilot.com/review/oh-matchaa.com',
#  'https://fr.trustpilot.com/review/eevad.com',
#  'https://fr.trustpilot.com/review/fruits-tropicaux.com',
#  'https://fr.trustpilot.com/review/hayuco.coffee',
#  'https://fr.trustpilot.com/review/lathebox.fr',
#  'https://fr.trustpilot.com/review/very-thes.com',
#  'https://fr.trustpilot.com/review/anomcafeclub.com',
#  'https://fr.trustpilot.com/review/www.palaisdesthes.com',
#  'https://fr.trustpilot.com/review/malindo.fr',
#  'https://fr.trustpilot.com/review/suedhang.org',
#  'https://fr.trustpilot.com/review/kumikomatcha.fr',
#  'https://fr.trustpilot.com/review/lavalleeducbd.fr',
#  'https://fr.trustpilot.com/review/broniiz.com',
#  'https://fr.trustpilot.com/review/www.chacunsoncafe.fr',
#  'https://fr.trustpilot.com/review/ileauxepices.com',
#  'https://fr.trustpilot.com/review/cbdtoulouse.fr',
#  'https://fr.trustpilot.com/review/pandatea.fr',
#  'https://fr.trustpilot.com/review/thesdirect.com',
#  'https://fr.trustpilot.com/review/strongcbd.fr',
#  'https://fr.trustpilot.com/review/www.anatae.fr',
#  'https://fr.trustpilot.com/review/cbdream-bordeaux.fr',
#  'https://fr.trustpilot.com/review/teaven.co',
#  'https://fr.trustpilot.com/review/ma-tassedethe.com',
#  'https://fr.trustpilot.com/review/42grammes.fr',
#  'https://fr.trustpilot.com/review/rituelduthe.fr',
#  'https://fr.trustpilot.com/review/feminitea.fr',
#  'https://fr.trustpilot.com/review/naturalsace.fr',
#  'https://fr.trustpilot.com/review/vitalmush-revolution.fr',
#  'https://fr.trustpilot.com/review/cafeographe.com',
#  'https://fr.trustpilot.com/review/santenaturesolution.com',
#  'https://fr.trustpilot.com/review/fleurdecbd-shop.com',
#  'https://fr.trustpilot.com/review/misterbean.fr',
#  'https://fr.trustpilot.com/review/maisonmatcha.co',
#  'https://fr.trustpilot.com/review/truth-and-right.com',
#  'https://fr.trustpilot.com/review/cafesmiguel.fr',
#  'https://fr.trustpilot.com/review/jardins-hermitage.com',
#  'https://fr.trustpilot.com/review/brulerie-chatelet.fr',
#  'https://fr.trustpilot.com/review/la-chanvriere.fr',
#  'https://fr.trustpilot.com/review/renaissance-tea.com',
#  'https://fr.trustpilot.com/review/compagnie-anglaise-des-thes.fr',
#  'https://fr.trustpilot.com/review/maidomatcha.com',
#  'https://fr.trustpilot.com/review/ikizen.fr',
#  'https://fr.trustpilot.com/review/laptitetasse.com',
#  'https://fr.trustpilot.com/review/sentea.fr',
#  'https://fr.trustpilot.com/review/cafes-bibal.fr',
#  'https://fr.trustpilot.com/review/graindinfusion.fr',
#  'https://fr.trustpilot.com/review/cafe-excellence.fr',
#  'https://fr.trustpilot.com/review/clintonhill.fr',
#  'https://fr.trustpilot.com/review/cafe-loule.fr',
#  'https://fr.trustpilot.com/review/mygoodtea.fr',
#  'https://fr.trustpilot.com/review/rosethe.fr',
#  'https://fr.trustpilot.com/review/toucheverte.fr',
#  'https://fr.trustpilot.com/review/atelierbraam.com',
#  'https://fr.trustpilot.com/review/cafes-pfaff.com',
#  'https://fr.trustpilot.com/review/pages.fr',
#  'https://fr.trustpilot.com/review/tyleaf.com',
#  'https://fr.trustpilot.com/review/tanesty.fr',
#  'https://fr.trustpilot.com/review/www.terre-des-thes.fr',
#  'https://fr.trustpilot.com/review/taureau-cafe.fr',
#  'https://fr.trustpilot.com/review/www.kusmitea.com',
#  'https://fr.trustpilot.com/review/lelabdubonheur.fr',
#  'https://fr.trustpilot.com/review/nunshen.com',
#  'https://fr.trustpilot.com/review/larbreathe.fr',
#  'https://fr.trustpilot.com/review/www.fortsdecafe.fr',
#  'https://fr.trustpilot.com/review/cafeintegral.fr',
#  'https://fr.trustpilot.com/review/matchamy.com',
#  'https://fr.trustpilot.com/review/www.shopleone.com',
#  'https://fr.trustpilot.com/review/hidrips.com',
#  'https://fr.trustpilot.com/review/blackidol.fr',
#  'https://fr.trustpilot.com/review/mdistribution.shop',
#  'https://fr.trustpilot.com/review/azcoffeesolutions.com',
#  'https://fr.trustpilot.com/review/thedorient.fr',
#  'https://fr.trustpilot.com/review/goute.org',
#  'https://fr.trustpilot.com/review/matchamatcha.fr',
#  'https://fr.trustpilot.com/review/www.lupicia.fr',
#  'https://fr.trustpilot.com/review/maxicoffee.com',
#  'https://fr.trustpilot.com/review/terramoka.fr',
#  'https://fr.trustpilot.com/review/greenma.fr',
#  'https://fr.trustpilot.com/review/au-paradis-du-cafe.com',
#  'https://fr.trustpilot.com/review/naturelhighcbd.fr',
#  'https://fr.trustpilot.com/review/cawatoes.fr',
#  'https://fr.trustpilot.com/review/www.top-saveur.fr',
#  'https://fr.trustpilot.com/review/odysseedesaromes.fr',
#  'https://fr.trustpilot.com/review/cafeterie-guillaume.com',
#  'https://fr.trustpilot.com/review/infuzea.fr',
#  'https://fr.trustpilot.com/review/nescaps.fr',
#  'https://fr.trustpilot.com/review/aubergeducafe.fr',
#  'https://fr.trustpilot.com/review/monmate.com',
#  'https://fr.trustpilot.com/review/mokao.co',
#  'https://fr.trustpilot.com/review/limmustea.com',
#  'https://fr.trustpilot.com/review/halmahera.fr',
#  'https://fr.trustpilot.com/review/ninitea.fr',
#  'https://fr.trustpilot.com/review/teatap.com',
#  'https://fr.trustpilot.com/review/lomi.coffee',
#  'https://fr.trustpilot.com/review/melitta.fr',
#  'https://fr.trustpilot.com/review/www.whittard.fr',
#  'https://fr.trustpilot.com/review/quick-coffee.fr',
#  'https://fr.trustpilot.com/review/www.herbesdechine.com',
#  'https://fr.trustpilot.com/review/solocaffemonorigine.fr',
#  'https://fr.trustpilot.com/review/bslim-france.com',
#  'https://fr.trustpilot.com/review/lobodis.com',
#  'https://fr.trustpilot.com/review/cafeengrains365.fr',
#  'https://fr.trustpilot.com/review/infusion.organic',
#  'https://fr.trustpilot.com/review/sofitelboutique.com',
#  'https://fr.trustpilot.com/review/tisanemiraculeuse.com',
#  'https://fr.trustpilot.com/review/www.albacaffe.fr',
#  'https://fr.trustpilot.com/review/letorref.com',
#  'https://fr.trustpilot.com/review/www.mapalga.fr',
#  'https://fr.trustpilot.com/review/loutsa.fr',
#  'https://fr.trustpilot.com/review/www.les2marmottes.fr',
#  'https://fr.trustpilot.com/review/crokfun.com',
#  'https://fr.trustpilot.com/review/merchants.groupon.fr',
#  'https://fr.trustpilot.com/review/nescafe.fr',
#  'https://fr.trustpilot.com/review/www.torrefaction.com',
#  'https://fr.trustpilot.com/review/kingcbd.fr',
#  'https://fr.trustpilot.com/review/cafetiere-tradition.com',
#  'https://fr.trustpilot.com/review/www.mariagefreres.com',
#  'https://fr.trustpilot.com/review/www.scott-gear.fr',
#  'https://fr.trustpilot.com/review/noailles.com',
#  'https://fr.trustpilot.com/review/matchabotanicals.fr',
#  'https://fr.trustpilot.com/review/lestorrefacteurs.cafe',
#  'https://fr.trustpilot.com/review/krups.fr',
#  'https://fr.trustpilot.com/review/caffem.fr',
#  'https://fr.trustpilot.com/review/www.coffee-box.fr',
#  'https://fr.trustpilot.com/review/selectcaffe.fr',
#  'https://fr.trustpilot.com/review/cbdparadise.fr',
#  'https://fr.trustpilot.com/review/cotesushi.com',
#  'https://fr.trustpilot.com/review/starbucks.fr',
#  'https://fr.trustpilot.com/review/capsulecafe.com',
#  'https://fr.trustpilot.com/review/nespresso.com/fr',
#  'https://fr.trustpilot.com/review/dammann.fr',
#  'https://fr.trustpilot.com/review/tassimo.fr',
#  'https://fr.trustpilot.com/review/cartenoire.fr',
#  'https://fr.trustpilot.com/review/www.special-t.fr',
#  'https://fr.trustpilot.com/review/caffescionti.com',
#  'https://fr.trustpilot.com/review/www.bonreveil.com',
#  'https://fr.trustpilot.com/review/myecocafe.fr',
#  'https://fr.trustpilot.com/review/www.selecta.fr',
#  'https://fr.trustpilot.com/review/www.dolce-gusto.fr',
#  'https://fr.trustpilot.com/review/cheef.fr',
#  'https://fr.trustpilot.com/review/dietbon.fr',
#  'https://fr.trustpilot.com/review/kitchendiet.fr',
#  'https://fr.trustpilot.com/review/kitchen-daily.fr',
#  'https://fr.trustpilot.com/review/mon-marche.fr',
#  'https://fr.trustpilot.com/review/qilibri.fr',
#  'https://fr.trustpilot.com/review/labrigadedevero.com',
#  'https://fr.trustpilot.com/review/lescommis.com',
#  'https://fr.trustpilot.com/review/commejaime.fr',
#  'https://fr.trustpilot.com/review/seazon.fr',
#  'https://fr.trustpilot.com/review/coqochef.fr',
#  'https://fr.trustpilot.com/review/quitoque.fr',
#  'https://fr.trustpilot.com/review/aussitotbon.fr',
#  'https://fr.trustpilot.com/review/regimebox.fr',
#  'https://fr.trustpilot.com/review/destia.fr',
#  'https://fr.trustpilot.com/review/saveursetvie.fr',
#  'https://fr.trustpilot.com/review/refectory.fr',
#  'https://fr.trustpilot.com/review/gocater.fr',
#  'https://fr.trustpilot.com/review/fredbox.fr',
#  'https://fr.trustpilot.com/review/silvousplait.co',
#  'https://fr.trustpilot.com/review/lesacjaune.fr',
#  'https://fr.trustpilot.com/review/superchef.co',
#  'https://fr.trustpilot.com/review/chefcoste.fr',
#  'https://fr.trustpilot.com/review/bienbonetbeau.com',
#  'https://fr.trustpilot.com/review/rebornfood.fr',
#  'https://fr.trustpilot.com/review/bchef.fr',
#  'https://fr.trustpilot.com/review/flymetothefood.com',
#  'https://fr.trustpilot.com/review/fast-and-curious.fr',
#  'https://fr.trustpilot.com/review/foodizz.fr',
#  'https://fr.trustpilot.com/review/www.cannes-yachts-booking.com',
#  'https://fr.trustpilot.com/review/dusoleildanslassiette.com',
#  'https://fr.trustpilot.com/review/changerlescodes.com',
#  'https://fr.trustpilot.com/review/djeliya.com',
#  'https://fr.trustpilot.com/review/rutabago.com',
#  'https://fr.trustpilot.com/review/mimiminceur.fr',
#  'https://fr.trustpilot.com/review/symphony.fr',
#  'https://fr.trustpilot.com/review/les-menus-services.com',
#  'https://fr.trustpilot.com/review/www.club-cafe-gourmet.fr',
#  'https://fr.trustpilot.com/review/www.lentrecotedeparis.fr',
#  'https://fr.trustpilot.com/review/livraisonadomicile07.fr',
#  'https://fr.trustpilot.com/review/restomalin.com',
#  'https://fr.trustpilot.com/review/feedly.fr',
#  'https://fr.trustpilot.com/review/labelleassiette.fr',
#  'https://fr.trustpilot.com/review/jour.fr',
#  'https://fr.trustpilot.com/review/feedmi.fr',
#  'https://fr.trustpilot.com/review/bofrost.fr',
#  'https://fr.trustpilot.com/review/dejbox.fr',
#  'https://fr.trustpilot.com/review/trend-home.fr',
#  'https://fr.trustpilot.com/review/deliveroo.fr',
#  'https://fr.trustpilot.com/review/nutri-naturel.com',
#  'https://fr.trustpilot.com/review/serie-radieuse.com',
#  'https://fr.trustpilot.com/review/veloboutiquepro.com',
#  'https://fr.trustpilot.com/review/onacook.com',
#  'https://fr.trustpilot.com/review/www.nordictemptations.com',
#  'https://fr.trustpilot.com/review/bretalg.boutique',
#  'https://fr.trustpilot.com/review/raya-boutique.fr',
#  'https://fr.trustpilot.com/review/otiec.fr',
#  'https://fr.trustpilot.com/review/www.pharmaciedesdrakkars.com',
#  'https://fr.trustpilot.com/review/willyantigaspi.fr',
#  'https://fr.trustpilot.com/review/joybuy.fr',
#  'https://fr.trustpilot.com/review/florfactory.fr',
#  'https://fr.trustpilot.com/review/beautysane.com',
#  'https://fr.trustpilot.com/review/asie-gourmande.fr',
#  'https://fr.trustpilot.com/review/ginseng-premium.com',
#  'https://fr.trustpilot.com/review/mybetterway.fr',
#  'https://fr.trustpilot.com/review/yumum.fr',
#  'https://fr.trustpilot.com/review/www.mathon.fr',
#  'https://fr.trustpilot.com/review/greenowl.fr',
#  'https://fr.trustpilot.com/review/moskera.com',
#  'https://fr.trustpilot.com/review/aesiel.com',
#  'https://fr.trustpilot.com/review/papapiadine.fr',
#  'https://fr.trustpilot.com/review/fermedubio.com',
#  'https://fr.trustpilot.com/review/thefrenchboxstore.com',
#  'https://fr.trustpilot.com/review/www.greenweez.com',
#  'https://fr.trustpilot.com/review/beansclub.fr',
#  'https://fr.trustpilot.com/review/nutriforce.fr',
#  'https://fr.trustpilot.com/review/hoope.fr',
#  'https://fr.trustpilot.com/review/avogel.fr',
#  'https://fr.trustpilot.com/review/greendogs.fr',
#  'https://fr.trustpilot.com/review/cadeauempoisonne.com',
#  'https://fr.trustpilot.com/review/nalkaa.com',
#  'https://fr.trustpilot.com/review/equilibre-cbd.com',
#  'https://fr.trustpilot.com/review/france-export-fv-online.com',
#  'https://fr.trustpilot.com/review/cocote.com',
#  'https://fr.trustpilot.com/review/fitoform.com',
#  'https://fr.trustpilot.com/review/benebono.fr',
#  'https://fr.trustpilot.com/review/magiccbd.fr',
#  'https://fr.trustpilot.com/review/vosneakers.com',
#  'https://fr.trustpilot.com/review/divinebox.fr',
#  'https://fr.trustpilot.com/review/www.dubruitdanslacuisine.fr',
#  'https://fr.trustpilot.com/review/monplancbd.fr',
#  'https://fr.trustpilot.com/review/davidvanille.com',
#  'https://fr.trustpilot.com/review/www.tempetedelouest.fr',
#  'https://fr.trustpilot.com/review/shamballa-shilajit.com',
#  'https://fr.trustpilot.com/review/belvibio.com',
#  'https://fr.trustpilot.com/review/www.vanille-naha-sava.fr',
#  'https://fr.trustpilot.com/review/lesruchesroyales.fr',
#  'https://fr.trustpilot.com/review/artsdelices.com',
#  'https://fr.trustpilot.com/review/amoseeds.com',
#  'https://fr.trustpilot.com/review/dockdesepices.com',
#  'https://fr.trustpilot.com/review/luxemorilles.com',
#  'https://fr.trustpilot.com/review/natura-baies.com',
#  'https://fr.trustpilot.com/review/mesepices.com',
#  'https://fr.trustpilot.com/review/slowinfusion.fr',
#  'https://fr.trustpilot.com/review/lepoivredekampot.fr',
#  'https://fr.trustpilot.com/review/popote-bebe.fr',
#  'https://fr.trustpilot.com/review/e-choppealternative.com',
#  'https://fr.trustpilot.com/review/kanyon-nutrition.fr',
#  'https://fr.trustpilot.com/review/dechandeau.com',
#  'https://fr.trustpilot.com/review/spiruline-armor.fr',
#  'https://fr.trustpilot.com/review/ouliva.fr',
#  'https://fr.trustpilot.com/review/lemondeentube.com',
#  'https://fr.trustpilot.com/review/avoabilio.fr',
#  'https://fr.trustpilot.com/review/terre-rouge.shop',
#  'https://fr.trustpilot.com/review/morillesauvage.com',
#  'https://fr.trustpilot.com/review/grandexotique.com',
#  'https://fr.trustpilot.com/review/asiamarche.fr',
#  'https://fr.trustpilot.com/review/drivetohome.fr',
#  'https://fr.trustpilot.com/review/www.thanh-binh.fr',
#  'https://fr.trustpilot.com/review/olala-cosmetics.com',
#  'https://fr.trustpilot.com/review/chronodrive.com',
#  'https://fr.trustpilot.com/review/green-paradise-shop.com',
#  'https://fr.trustpilot.com/review/sourceshop.fr',
#  'https://fr.trustpilot.com/review/bredele.boutique',
#  'https://fr.trustpilot.com/review/lecomptoirdekatia.com',
#  'https://fr.trustpilot.com/review/delight-cbd.com',
#  'https://fr.trustpilot.com/review/mont-shilajit.com',
#  'https://fr.trustpilot.com/review/dinistore.fr',
#  'https://fr.trustpilot.com/review/www.sporuline.com',
#  'https://fr.trustpilot.com/review/la-brouette-occitane.com',
#  'https://fr.trustpilot.com/review/osezvotresante.com',
#  'https://fr.trustpilot.com/review/dirtysmoka.fr',
#  'https://fr.trustpilot.com/review/perlenoireshop.fr',
#  'https://fr.trustpilot.com/review/www.universpharmacie.fr',
#  'https://fr.trustpilot.com/review/candydukes.com',
#  'https://fr.trustpilot.com/review/cbdtech.fr',
#  'https://fr.trustpilot.com/review/francementbon.com',
#  'https://fr.trustpilot.com/review/cbdoo.store',
#  'https://fr.trustpilot.com/review/shopnature.fr',
#  'https://fr.trustpilot.com/review/tesai-mate.fr',
#  'https://fr.trustpilot.com/review/so-mauricette.fr',
#  'https://fr.trustpilot.com/review/drivelafourmiliere.com',
#  'https://fr.trustpilot.com/review/habeshakitchen.com',
#  'https://fr.trustpilot.com/review/sauceshabans.fr',
#  'https://fr.trustpilot.com/review/harctic.com',
#  'https://fr.trustpilot.com/review/les-epices-curieuses.com',
#  'https://fr.trustpilot.com/review/ocabas.com',
#  'https://fr.trustpilot.com/review/mesvoisinsproducteurs.com',
#  'https://fr.trustpilot.com/review/tompress.fr',
#  'https://fr.trustpilot.com/review/highsociety.fr',
#  'https://fr.trustpilot.com/review/mybudshop.fr',
#  'https://fr.trustpilot.com/review/www.annachi.fr',
#  'https://fr.trustpilot.com/review/neptuneelements.com',
#  'https://fr.trustpilot.com/review/kriss-laure.com',
#  'https://fr.trustpilot.com/review/ubbabio.com',
#  'https://fr.trustpilot.com/review/lamaisonjahazi.com',
#  'https://fr.trustpilot.com/review/lindespyrenees.fr',
#  'https://fr.trustpilot.com/review/provencalbox.com',
#  'https://fr.trustpilot.com/review/zone-expo.ca',
#  'https://fr.trustpilot.com/review/maisonproteine.com',
#  'https://fr.trustpilot.com/review/lidealist.store',
#  'https://fr.trustpilot.com/review/lespetitspois.com',
#  'https://fr.trustpilot.com/review/tomato-n-co.com',
#  'https://fr.trustpilot.com/review/sweetpepper.fr',
#  'https://fr.trustpilot.com/review/18h15.fr',
#  'https://fr.trustpilot.com/review/okr.fr',
#  'https://fr.trustpilot.com/review/paniergaia.com',
#  'https://fr.trustpilot.com/review/jow.fr',
#  'https://fr.trustpilot.com/review/www.ecomiam.com',
#  'https://fr.trustpilot.com/review/hyperbio.com',
#  'https://fr.trustpilot.com/review/aupaysducbd.com',
#  'https://fr.trustpilot.com/review/ibericoexport.com',
#  'https://fr.trustpilot.com/review/premiumepices.com',
#  'https://fr.trustpilot.com/review/www.tocopop.com',
#  'https://fr.trustpilot.com/review/sainpleat.fr',
#  'https://fr.trustpilot.com/review/terradinatura.com',
#  'https://fr.trustpilot.com/review/boutiquenaturellement.com',
#  'https://fr.trustpilot.com/review/cbiendose.com',
#  'https://fr.trustpilot.com/review/shop.aromabe.fr',
#  'https://fr.trustpilot.com/review/organic-gourmet.fr',
#  'https://fr.trustpilot.com/review/myshilaya.com',
#  'https://fr.trustpilot.com/review/super-mamas.fr',
#  'https://fr.trustpilot.com/review/noblegousse.fr',
#  'https://fr.trustpilot.com/review/vanissa.fr',
#  'https://fr.trustpilot.com/review/moonsowl.com',
#  'https://fr.trustpilot.com/review/ecodya.com',
#  'https://fr.trustpilot.com/review/feuillagesdumonde.com',
#  'https://fr.trustpilot.com/review/lisaleber-dietethique.com',
#  'https://fr.trustpilot.com/review/services-a-dhom.fr',
#  'https://fr.trustpilot.com/review/ladatchadekatia.fr',
#  'https://fr.trustpilot.com/review/miel-empire.com',
#  'https://fr.trustpilot.com/review/biovie.fr',
#  'https://fr.trustpilot.com/review/lescolisduboucher.com',
#  'https://fr.trustpilot.com/review/www.lagourmetbox.com',
#  'https://fr.trustpilot.com/review/saveursdesterroirs.net',
#  'https://fr.trustpilot.com/review/vgreen.fr',
#  'https://fr.trustpilot.com/review/scnutra.eu',
#  'https://fr.trustpilot.com/review/calysco.fr',
#  'https://fr.trustpilot.com/review/effet-mere.fr',
#  'https://fr.trustpilot.com/review/mynutriform.com',
#  'https://fr.trustpilot.com/review/haruharu.fr',
#  'https://fr.trustpilot.com/review/soukouroux.com',
#  'https://fr.trustpilot.com/review/ginaepices.com',
#  'https://fr.trustpilot.com/review/lafourche.fr',
#  'https://fr.trustpilot.com/review/www.potagercity.fr',
#  'https://fr.trustpilot.com/review/nouvojour.fr',
#  'https://fr.trustpilot.com/review/lecoqgourmet.fr',
#  'https://fr.trustpilot.com/review/merciwalter.com',
#  'https://fr.trustpilot.com/review/gourmetsansgene.com',
#  'https://fr.trustpilot.com/review/multiboutik.fr',]

In [142]:
# # 3. scraper les reviews
# for site_url in urls:

#     print(f"Entreprise : {site_url}")

#     current_url = site_url

#     while True:

#         driver.get(current_url)
#         time.sleep(3)

#         try:
#             main_content = driver.find_element(
#                 By.CLASS_NAME,
#                 "styles_mainContent__d9oos"
#             )

#             articles = main_content.find_elements(
#                 By.TAG_NAME,
#                 "article"
#             )

#             for article in articles:

#                 # contenu review
#                 try:
#                     try:
#                         element = article.find_element(
#                             By.TAG_NAME,
#                             "p"
#                         )
#                     except:
#                         element = article.find_element(
#                             By.TAG_NAME,
#                             "h2"
#                         )

#                     content = element.text.strip()

#                     if len(content) < 3:
#                         continue

#                 except:
#                     continue

#                 # étoiles
#                 try:
#                     stars = article.find_element(
#                         By.CLASS_NAME,
#                         "styles_reviewHeader__DzoAZ"
#                     ).get_attribute(
#                         "data-service-review-rating"
#                     )

#                     label = get_label(stars)

#                 except:
#                     continue

#                 reviews_data.append({
#                     "content": content,
#                     "label": label,
#                     "type": "commentaire",
#                     "source": site_url
#                 })


#             # pagination reviews
#             try:
#                 pagination = main_content.find_element(
#                     By.CSS_SELECTOR,
#                     '[name="pagination-button-next"]'
#                 )

#                 next_url = pagination.get_attribute("href")

#                 if not next_url:
#                     break

#                 current_url = next_url

#             except:
#                 break

#         except Exception as e:
#             print(e)
#             break

In [143]:
# driver.quit()

In [144]:
# df = pd.DataFrame(reviews_data)

In [ ]:
df =  pd.read_csv("../data/trustpilot_reviews.csv")

In [146]:
df.dropna(inplace=True)

In [147]:
df.head()

,content,label,type,source
0,Parfum de haute qualité et excellent.je recomm...,pos,commentaire,https://fr.trustpilot.com/review/ouwayss.com
1,Ces parfums Gogeta et Vida o muerte sont de vé...,pos,commentaire,https://fr.trustpilot.com/review/ouwayss.com
2,"Vendeur très fiable et professionnel, à l’écou...",pos,commentaire,https://fr.trustpilot.com/review/ouwayss.com
3,Très bons conseils et connaissance des produit...,pos,commentaire,https://fr.trustpilot.com/review/ouwayss.com
4,J’ai reçu rapidement le parfum . J’ai choisis ...,pos,commentaire,https://fr.trustpilot.com/review/ouwayss.com

In [148]:
df.replace('\n', ' ', regex=True, inplace=True)
df.replace('\r', ' ', regex=True, inplace=True)

In [149]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53776 entries, 0 to 53775
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   content  53776 non-null  object
 1   label    53776 non-null  object
 2   type     53776 non-null  object
 3   source   53776 non-null  object
dtypes: object(4)
memory usage: 1.6+ MB

In [150]:
df.sample(10)

,content,label,type,source
47814,Réponse de Hayuco Coffee Roasters,pos,commentaire,https://fr.trustpilot.com/review/hayuco.coffee
48513,Le site est très bien fait on y trouve que Cla...,pos,commentaire,https://fr.trustpilot.com/review/www.palaisdes...
17311,Livraison rapide. Colis bien protégé. Le rendu...,pos,commentaire,https://fr.trustpilot.com/review/atelierspirit.fr
35203,C'est parfait je retrouve les goût du réglisse...,pos,commentaire,https://fr.trustpilot.com/review/lareglisserie.fr
27785,J’ai beaucoup aimé le boire après ma séance de...,pos,commentaire,https://fr.trustpilot.com/review/drinknuoro.com
33058,J'adore cet appareil que j'ai recommandé et of...,neg,commentaire,https://fr.trustpilot.com/review/www.detoximix...
51761,Ma commande suite à une confusion Nespresso pr...,neg,commentaire,https://fr.trustpilot.com/review/cafe-excellen...
25575,Expédition rapide. Produits bien emballés.,pos,commentaire,https://fr.trustpilot.com/review/www.lesartist...
32164,Excellent service et très copieux 😍,pos,commentaire,https://fr.trustpilot.com/review/brunchytime.fr
39592,"Excellent site Web, commande très facile, et l...",pos,commentaire,https://fr.trustpilot.com/review/lefrenchbiscu...

In [151]:
df[df["label"] == "neg"].shape

(6392, 4)

In [152]:
df[df["label"] == "pos"].shape

(45823, 4)

In [153]:
df.drop_duplicates(inplace=True)
# df.drop(df[df['label'] == 'neutre'].index, inplace=True)

In [154]:
from sklearn.utils import shuffle

In [155]:
pos_df = df[df["label"] == "pos"]
neg_df = df[df["label"] == "neg"]
neu_df= df[df["label"] == "neutre"]

In [156]:
pos_df =shuffle(pos_df)
pos_df.reset_index(inplace=True, drop=True)
pos_df

,content,label,type,source
0,J'étais septique lors de ma première commande ...,pos,commentaire,https://fr.trustpilot.com/review okamatcha.com
1,J'ai déjà eu l'occasion de rendre visite à l'E...,pos,commentaire,https://fr.trustpilot.com/review/entrepotitali...
2,"très content, réactif et livraison rapide. au ...",pos,commentaire,https://fr.trustpilot.com/review/www.cavepurju...
3,Je suis passée ce soir à la boulangerie la Mie...,pos,commentaire,https://fr.trustpilot.com/review/www.lamiecali...
4,Merci pour votre professionnalisme et votre at...,pos,commentaire,https://fr.trustpilot.com/review/vignartea.fr
...,...,...,...,...
44687,Tout parfait ! Je recommande ce site,pos,commentaire,https://fr.trustpilot.com/review/tresorsdebacc...
44688,Expédition et livraison tres rapide . Excellen...,pos,commentaire,https://fr.trustpilot.com/review/cavedantoine.com
44689,J'ai acheté le pack découverte avec une gourde...,pos,commentaire,https://fr.trustpilot.com/review/hydrology.fr
44690,Personne très sérieuse. Emballage parfait. Liv...,pos,commentaire,https://fr.trustpilot.com/review/arcencieldego...
44691,bon site efficace bon choix livraison rapide,pos,commentaire,https://fr.trustpilot.com/review/drinksco.fr

In [157]:
neg_df =shuffle(neg_df)
neg_df.reset_index(inplace=True, drop=True)
neg_df

,content,label,type,source
0,Commande préparé rapidement livraison rapide P...,neg,commentaire,https://fr.trustpilot.com/review/arcencieldego...
1,"VendEUSES peu souriantes, et parfois presque d...",neg,commentaire,https://fr.trustpilot.com/review/feuillette.fr
2,J'ai reçu comme cadeau cette boite à Champigno...,neg,commentaire,https://fr.trustpilot.com/review/www.laboiteac...
3,Bonjour J'ai acheté dès brioches pasquier de t...,neg,commentaire,https://fr.trustpilot.com/review/pasquier.fr
4,Le goût du cocot ne jamais a faire. Je ne fera...,neg,commentaire,https://fr.trustpilot.com/review/kitkat.fr
...,...,...,...,...
6367,Commande passée le 05 janvier 2026 et aucune l...,neg,commentaire,https://fr.trustpilot.com/review/lecartelfranc...
6368,J ai un lave vaisselle encastré dès sa livrais...,neg,commentaire,https://fr.trustpilot.com/review/rosieres.fr
6369,Bonjour Je reçois ce questionnaire de satisfai...,neg,commentaire,https://fr.trustpilot.com/review/payzan.fr
6370,"Je suis très insatisfait(e), je n'avais pas fa...",neg,commentaire,https://fr.trustpilot.com/review/eevad.com
6371,Beaucoup trop d'erreur de commande et de décom...,neg,commentaire,https://fr.trustpilot.com/review/www.la-tourne...

In [158]:
# neg_df = neg_df[:len(neu_df)]
pos_df = pos_df[:len(neg_df)]

In [159]:
neg_df.shape, pos_df.shape

((6372, 4), (6372, 4))

In [160]:
df = pd.concat([neg_df, pos_df], axis=0)

In [161]:
df.head()

,content,label,type,source
0,Commande préparé rapidement livraison rapide P...,neg,commentaire,https://fr.trustpilot.com/review/arcencieldego...
1,"VendEUSES peu souriantes, et parfois presque d...",neg,commentaire,https://fr.trustpilot.com/review/feuillette.fr
2,J'ai reçu comme cadeau cette boite à Champigno...,neg,commentaire,https://fr.trustpilot.com/review/www.laboiteac...
3,Bonjour J'ai acheté dès brioches pasquier de t...,neg,commentaire,https://fr.trustpilot.com/review/pasquier.fr
4,Le goût du cocot ne jamais a faire. Je ne fera...,neg,commentaire,https://fr.trustpilot.com/review/kitkat.fr

In [162]:
df.drop(columns=["source"], inplace=True)

In [163]:
df["content"] = df["content"].apply(lambda x: x.lower())

In [ ]:
df = shuffle(df)
df.reset_index(inplace=True, drop=True)
df.to_csv("data/sentiment_data.csv", index=False, encoding="utf-8-sig")

In [165]:
df.sample(frac=0.1, random_state=42)

                                                 content label         type
4015   cette chicorée bonne pour la santé est aussi t...   pos  commentaire
10105  moment très agréable, merci pour cette dégusta...   pos  commentaire
7132   envoi rapide et produit conforme à la commande...   pos  commentaire
8291   vous avez utilisé mon adresse mail par erreur,...   neg  commentaire
5389   emballage trop léger juste une enveloppe à bul...   pos  commentaire
...                                                  ...   ...          ...
8358   hausse considerable de prix baisse de qualité ...   neg  commentaire
2029   un bon choix de bières, de belles découvertes,...   pos  commentaire
5635   comme pour tous leurs services-que ce soit en ...   neg  commentaire
346                     rapidité de l envoi. très fiable   pos  commentaire
2973   une très bonne sélection de vins de grande qua...   pos  commentaire

[1274 rows x 3 columns]

In [166]:
import emoji

In [167]:
df['content'].apply(
    lambda x: any(char in emoji.EMOJI_DATA for char in str(x))
).sum()

np.int64(560)

In [168]:
df['content_without_emojis'] = df['content'].apply(
        lambda x: emoji.demojize(str(x), language='fr')
    )

In [169]:
df['content_without_emojis'].apply(
    lambda x: any(char in emoji.EMOJI_DATA for char in str(x))
).sum()

np.int64(0)

In [170]:
df.head()

,content,label,type,content_without_emojis
0,les draps commandés - très onéreux - sont mal ...,neg,commentaire,les draps commandés - très onéreux - sont mal ...
1,impossible de les joindre suite à une commande...,neg,commentaire,impossible de les joindre suite à une commande...
2,dommage qu'on ne puisse pas noter rapidement l...,neg,commentaire,dommage qu'on ne puisse pas noter rapidement l...
3,"7,80 pour une crêpe sans nutella +une piteuse ...",neg,commentaire,"7,80 pour une crêpe sans nutella +une piteuse ..."
4,calendrier de l’avent commandé le 25/11 livrai...,neg,commentaire,calendrier de l’avent commandé le 25/11 livrai...

In [171]:
import spacy
nlp = spacy.load("fr_core_news_sm")
import string

In [172]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [ ]:
df["content_without_emojis"].apply(lambda x: " ".join([char for char in x if char not in string.punctuation]))

0        l e s   d r a p s   c o m m a n d é s     t r ...
1        i m p o s s i b l e   d e   l e s   j o i n d ...
2        d o m m a g e   q u o n   n e   p u i s s e   ...
3        7 8 0   p o u r   u n e   c r ê p e   s a n s ...
4        c a l e n d r i e r   d e   l ’ a v e n t   c ...
                               ...
12739    c o m m a n d e   n o n   r e ç u   a u   b o ...
12740    b e l l e   a r n a q u e   j a u r a i s   d ...
12741    c ’ e s t   u n e   v r a i e   b l a g u e   ...
12742    e x c e l l e n t   c o m m e   t o u j o u r ...
12743    s a n d w i c h   d é g o û t a n t   a v a n ...
Name: content_without_emojis, Length: 12744, dtype: object

In [174]:

def preprocess_text(text):
    text = "".join([char for char in text if char not in string.punctuation])
    doc = nlp(text)    
    return [
        token.lemma_
        for token in doc
        if not token.is_punct
        and not token.is_stop
        and not token.is_space
    ]

In [175]:
df['content_preprocessed'] = df['content_without_emojis'].apply(preprocess_text)
df.head()

,content,label,type,content_without_emojis,content_preprocessed
0,les draps commandés - très onéreux - sont mal ...,neg,commentaire,les draps commandés - très onéreux - sont mal ...,"[drap, commandé, onéreux, mal, ajuster, trop, ..."
1,impossible de les joindre suite à une commande...,neg,commentaire,impossible de les joindre suite à une commande...,"[impossible, joindre, suite, commande, avoir, ..."
2,dommage qu'on ne puisse pas noter rapidement l...,neg,commentaire,dommage qu'on ne puisse pas noter rapidement l...,"[dommage, quon, pouvoir, noter, rapidement, al..."
3,"7,80 pour une crêpe sans nutella +une piteuse ...",neg,commentaire,"7,80 pour une crêpe sans nutella +une piteuse ...","[780, crêpe, nuteller, piteux, boul, glace, tr..."
4,calendrier de l’avent commandé le 25/11 livrai...,neg,commentaire,calendrier de l’avent commandé le 25/11 livrai...,"[calendrier, aver, commander, 2511, livraison,..."

In [176]:
df.to_csv("sentiment_data.csv", index=False, encoding="utf-8-sig")

In [177]:
df['label'].value_counts()

label
neg    6372
pos    6372
Name: count, dtype: int64